# Use 'Egypt 1951' as the reference and root, following Mencattelli et al, 2023
# https://www.nature.com/articles/s41467-023-42185-7
reference: "defaults/all-lineages/reference.gb"
root: "mid_point"
build: "all-lineages"

subsample:
  samples:
    region:
      query: is_lab_host != 'true'
      query_columns:
        - is_lab_host:str
      min_length: 8200
      group_by:
        - region
        - year
      max_sequences: 3000
      exclude:
        - defaults/exclude.txt
      include:
        - defaults/include.txt

refine:
  treetime_params: --coalescent opt --date-inference marginal --date-confidence --keep-polytomies --clock-rate 0.000755

export:
  auspice_config: "defaults/all-lineages/auspice_config.json"
