subsample:
  defaults:
    query: is_lab_host != 'true'
    query_columns:
      - is_lab_host:str
    min_length: 8200
    exclude:
      - defaults/exclude.txt
    include:
      - defaults/include.txt
  samples:
    region:
      group_by:
        - region
        - year
      subsample_max_sequences: 3000
