subsample:
  defaults:
    query: is_lab_host != 'true'
    query_columns:
      - is_lab_host:str
    min_length: 8200
    exclude:
      - defaults/exclude.txt
    include:
      - defaults/include.txt
  samples:
    focal:
      query: division == 'WA'
      subsample_max_sequences: 300
    contextual_similar:
      query: country == 'USA' & division != 'WA'
      proximity_target: focal
      subsample_max_sequences: 25
    contextual_other:
      query: country == 'USA' & division != 'WA'
      subsample_max_sequences: 25
      exclude_samples:
        - contextual_similar
    background:
      query: country != 'USA'
      group_by:
        - country
        - month
      subsample_max_sequences: 50
  output:
    - background
    - contextual_similar
    - contextual_other
    - focal
