subsample:
  samples:
    region:
      query: is_lab_host != 'true'
      query_columns:
        - is_lab_host:str
      min_length: 8200
      group_by:
        - region
        - year
      subsample_max_sequences: 3000
      exclude:
        - defaults/exclude.txt
    force_include:
      exclude_all: true
      include:
        - defaults/include.txt
