# This configuration file should contain all required configuration parameters
# for the ingest workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

ppx_fetch:
  seqs: https://lapis.pathoplexus.org/west-nile/sample/unalignedNucleotideSequences?versionStatus=LATEST_VERSION
  meta: https://lapis.pathoplexus.org/west-nile/sample/details?dataFormat=csv&versionStatus=LATEST_VERSION

# Config parameters related to the curate pipeline
curate:
  # The path to the local geolocation rules within the pathogen repo
  # The path should be relative to the ingest directory.
  local_geolocation_rules: "defaults/geolocation-rules.tsv"
  # This is the first step in the pipeline, so any references to field names in the configs below should use the new field names
  field_map:
    accessionVersion: PPX_accession
    insdcAccessionFull: INSDC_accession
    insdcRawReadsAccession: sra_accession
    displayName: strain
    geoLocCountry: country
    geoLocAdmin1: division
    geoLocAdmin2: location
    sampleCollectionDate: date
    earliestReleaseDate: date_submitted
    hostNameCommon: host
    isLabHost: is_lab_host
    dataUseTermsRestrictedUntil: restrictedUntil
    dataUseTermsUrl: dataUseTerms__url
    authors: full_authors
    authorAffiliations: institution
  # List of date fields to standardize to ISO format YYYY-MM-DD
  date_fields: ["date", "date_submitted"]
  # List of expected date formats that are present in the date fields provided above
  # These date formats should use directives expected by datetime
  # See https://docs.python.org/3.9/library/datetime.html#strftime-and-strptime-format-codes
  expected_date_formats: ["%Y", "%Y-%m", "%Y-%m-%d", "%Y-%m-%dT%H:%M:%SZ"]
  titlecase:
    # List of string fields to titlecase
    fields: ["region", "country", "division", "location"]
    # List of abbreviations not cast to titlecase, keeps uppercase
    abbreviations: ["USA"]
    # Articles that should not be cast to titlecase
    articles: [
      "and", "d", "de", "del", "des", "di", "do", "en", "l", "la", "las", "le",
      "los", "nad", "of", "op", "sur", "the", "y"
    ]
  # Metadata field that contains the list of authors associated with the sequence
  authors_field: "full_authors"
  # Default value to use if the authors field is empty
  authors_default_value: "?"
  # Name to use for the generated abbreviated authors field
  abbr_authors_field: "authors"
  # Path to the manual annotations file
  # The path should be relative to the ingest directory
  annotations: "defaults/annotations.tsv"
  # The ID field in the metadata to use to merge the manual annotations
  annotations_id: "accession"
  # The ID field in the metadata to use as the sequence id in the output FASTA file
  output_id_field: "accession"
  # The field in the NDJSON record that contains the actual genomic sequence
  output_sequence_field: "sequence"
  # The field in the NDJSON record that contains the actual Pathoplexus accession
  pathoplexus_accession: 'PPX_accession'
  # The field in the NDJSON record that contains the actual INSDC accession
  insdc_accession: 'INSDC_accession'

  # The list of metadata columns to keep in the final output of the curation pipeline.
  metadata_columns: [
    'accession',
    'PPX_accession',
    'PPX_accession__url',
    'INSDC_accession',
    'INSDC_accession__url',
    #'strain',
    'date',
    #'updated',
    'region',
    'country',
    'division',
    'location',
    'state',
    'host',
    'host_genus',
    'host_type',
    'is_lab_host',
    #'date_submitted',
    #'sra_accession',
    'authors',
    'institution',
    'dataUseTerms',
    'dataUseTerms__url',
    'restrictedUntil',
    'length',
  ]

nextclade:
  nextclade_dataset_path: '../nextclade/dataset'
  nextclade_field: 'clade_membership'
  nextclade_id: 'accession'

pathoplexus:
  URL: 'https://lapis.pathoplexus.org/west-nile/sample/details'
  fields: 'accession,lineage'
  accession_field: 'accession'

ppx_metadata_fields:
 - "accessionVersion"
 - "accession"
 - "version"
 - "submitter"
 - "groupName"
 - "submittedDate"
 - "releasedDate"
 - "dataUseTerms"
 - "dataUseTermsRestrictedUntil"
 - "dataUseTermsUrl"
 - "assemblyReferenceGenomeAccession"
 - "authorAffiliations"
 - "authors"
 - "bioprojectAccession"
 - "biosampleAccession"
 - "completeness"
 - "displayName"
 - "earliestReleaseDate"
 - "frameShifts"
 - "geoLocAdmin1"
 - "geoLocAdmin2"
 - "geoLocCity"
 - "geoLocCountry"
 - "geoLocLatitude"
 - "geoLocLongitude"
 - "geoLocSite"
 - "hostAge"
 - "hostAgeBin"
 - "hostDisease"
 - "hostGender"
 - "hostHealthOutcome"
 - "hostHealthState"
 - "hostNameCommon"
 - "hostOriginCountry"
 - "hostVaccinationStatus"
 - "insdcAccessionBase"
 - "insdcAccessionFull"
 - "insdcRawReadsAccession"
 - "insdcVersion"
 - "isLabHost"
 - "length"
 - "ncbiReleaseDate"
 - "ncbiSourceDb"
 - "ncbiSubmitterCountry"
 - "ncbiUpdateDate"
 - "ncbiVirusName"
 - "ncbiVirusTaxId"
 - "purposeOfSampling"
 - "purposeOfSequencing"
 - "qualityControlDetails"
 - "qualityControlDetermination"
 - "qualityControlIssues"
 - "qualityControlMethodName"
 - "qualityControlMethodVersion"
 - "sampleCollectionDate"
 - "sampleCollectionDateRangeLower"
 - "sampleCollectionDateRangeUpper"
 - "sampleType"
 - "totalAmbiguousNucs"
 - "totalDeletedNucs"
 - "totalFrameShifts"
 - "totalInsertedNucs"
 - "totalSnps"
 - "totalUnknownNucs"
 - "travelHistory"
