#! /usr/bin/env python3

import argparse
import json
from sys import stdin, stdout


def parse_args():
    parser = argparse.ArgumentParser(
        description="Reformat a NCBI Virus NDJSON file for a pathogen build to ensure new columns exist. Necessary to augur curate apply-record-annotations."
    )
    parser.add_argument("--metadata-columns", nargs="+",
        help="List of fields to ensure exists in the NDJSON. Will create missing columns with empty values.")
    return parser.parse_args()

def main():
    args = parse_args()

    for index, record in enumerate(stdin):
        record = json.loads(record)
        for col in args.metadata_columns:
            if col not in record:
                record[col] = ""
        stdout.write(json.dumps(record) + "\n")

if __name__ == "__main__":
    main()
